services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: sh -c "bun x prisma db push && bun start"
    depends_on:
      - db
    ports:
      - '8080:8080'
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/messages
      - POSTGRES_PASSWORD=postgres
      - PORT=8080
    networks:
      - ps
  db:
    restart: always
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=messages
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - ps

volumes:
  db:

networks:
  ps:
